# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_16.4.0.app/Contents/Developer

jobs:
  main:
    name: SwiftPM Build
    runs-on: macos-15
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: swift build
        run: swift build
